Feature/housekeeper activities
Eimvi/HotelUnsij-Angular pull request #25
Opened 2022-05-30 16:28 UTC by Hipo-ui

## Hisoria actividades de ama de casa

### Se desarrolló el módulo en donde la ama de llaves puede ver sus actividades asignadas.

<img width="523" alt="Captura de Pantalla 2022-05-30 a la(s) 11 13 46 a m" src="https://user-images.githubusercontent.com/79946962/171031823-93b020ac-a442-4d36-8251-3482cfae02f3.png">

<img width="523" alt="Captura de Pantalla 2022-05-30 a la(s) 11 14 01 a m" src="https://user-images.githubusercontent.com/79946962/171031817-f7534840-5446-4017-8dda-acc1e93b55a1.png">

2022-05-30 18:24 UTC, Eimvi requested changes

2022-05-31 04:59 UTC, Hipo-ui commented on src/app/housekeeper/services/housekeeper-activities.service.ts
> +  previousReportCreate(previousReport: FormData, id:string){
He eliminado esta parte del código

2022-05-31 04:59 UTC, Hipo-ui commented on src/app/housekeeper/services/housekeeper-activities.service.ts
> +  posteriorReportCreate(posteriorReport: FormData, id:string){
He eliminado esta parte del código

2022-05-31 04:59 UTC, Hipo-ui commented on src/app/housekeeper/services/housekeeper-activities.service.ts
> +import { ToastrService } from 'ngx-toastr';
He eliminado ToastrService del servicio

2022-05-31 15:20 UTC, Eimvi requested changes

2022-05-31 15:20 UTC, Eimvi commented on src/app/housekeeper/components/housekeeper-activities/housekeeper-activities.component.html
> +            <button class="btn btn-primary" [routerLink]="['/maid/reports']" [queryParams]="{id: activity.id}" >Detalles</button>
Maid?

2022-06-01 03:15 UTC, Hipo-ui commented on src/app/housekeeper/components/housekeeper-activities/housekeeper-activities.component.html
> +            <button class="btn btn-primary" [routerLink]="['/maid/reports']" [queryParams]="{id: activity.id}" >Detalles</button>
Corregido

2022-06-01 15:41 UTC, merged