Feature/housekeeper inventory
Eimvi/HotelUnsij-Angular pull request #30
Opened 2022-06-09 22:54 UTC by Hipo-ui

## Hisoria inventarios de ama de casa (Lista de registros)

### Se desarrolló el módulo en donde la ama de llaves puede los registros de inventarios 

<img width="519" alt="Captura de Pantalla 2022-06-09 a la(s) 5 53 29 p m" src="https://user-images.githubusercontent.com/79946962/172958417-ef67b4d3-a0fe-4d1f-becb-96f0b675dfff.png">

2022-06-09 23:07 UTC, Eimvi requested changes

2022-06-09 23:07 UTC, Eimvi commented on src/app/housekeeper/interfaces/inventory.interface.ts
> +export interface  RootObject {
Esto debe llamarse Body

2022-06-09 23:07 UTC, Eimvi commented on src/app/housekeeper/interfaces/inventory.interface.ts
> +export interface Body {
Esto debe llamarse Register

2022-06-09 23:07 UTC, Eimvi commented on src/app/housekeeper/interfaces/inventory.interface.ts
> +export interface Amenidade {
Esto debe llamarse Amenidades

2022-06-10 01:14 UTC, Hipo-ui commented on src/app/housekeeper/interfaces/inventory.interface.ts
> +export interface  RootObject {
Corregido

2022-06-10 01:14 UTC, Hipo-ui commented on src/app/housekeeper/interfaces/inventory.interface.ts
> +export interface Body {
Corregido

2022-06-10 01:43 UTC, merged